### ISSUE TITLE
Thumbnail "undefined" in addon: org.openhab.binding.moonraker

### ISSUE THREAD

**Issue by crimsonclyde** [zenzmatz/openhab-addons#2]
## Expected Behavior
Thumbnail is not working or I missed some settings which I am not aware of

## Current Behavior
Everything works. Copied add-on into /openhab/addons/ and started it via bundle:start org.openhab.binding.moonraker. Thing configuration works and items as well. Except of the thumbnail, if you add the item you get "UNDEF" and the thumbnail is not shown.

## Steps to Reproduce (for Bugs)
1. Install add-on
2. Configure IP for Moonraker
3. Add new item "Thumbnail"

![image](https://user-images.githubusercontent.com/2612152/152118259-3e21dd89-8681-4dc6-9e33-4d3c5b91b20d.png)

![image](https://user-images.githubusercontent.com/2612152/152119158-cf05714f-78b0-4646-89b8-311accc192e3.png)

## Context
Not urgent, might be a configuration error.
Is there a way with Karaf to provide a log for the add-on, I would be happy to attach it here.

## Your Environment
* Version used: OpenHab3.2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Synology NAS 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Docker environment
* Add-on Version: org.openhab.binding.moonraker-3.2.0-SNAPSHOT.jar

**Comment by zenzmatz** [comment]
Please try new release with following jar:

https://github.com/zenzmatz/openhab-addons/releases/download/Bugfix/org.openhab.binding.moonraker-3.2.0-SNAPSHOT.jar

In the karaf console, you can switch between info and trace with following command:

log:set INFO org.openhab.binding.moonraker                                                                                                                                                                                                                       
log:set TRACE org.openhab.binding.moonraker

**Comment by crimsonclyde** [comment]
Awesomeness!
Works like a charm - thanks for helping! Thought I missed something :)

Not related to this request:
Just a hint: Have you considered getting the camera screenshot instead of the preview?
